domain: francescopodcast.it
encoding: utf-8
url: 'https://francescopodcast.it'
plugins:
    - jekyll-sitemap
    - jekyll-compress-images
sass:
    sass_dir: ./_scss
exclude:
    - dev/
    - README.md
