domain: francescopodcast.it
url: 'https://www.francescopodcast.it'
plugins:
    - jekyll-sitemap
    - jekyll-compress-images
sass:
    sass_dir: ./_scss
exclude:
    - dev/
compress_images:
    images_path: 'assets/images/**/*.{gif,png,jpg,jpeg,svg}'
